In [2]:
import os
os.listdir()

['.ipynb_checkpoints',
 '00_Basic_Summary',
 '00_Basic_Summary.zip',
 '01_DX_Class_Data_Set.zip',
 '02_Test_Data_Set',
 '02_Test_Data_Set_2.zip',
 'bike.csv',
 'classification_data_01.csv',
 'diamonds.csv',
 'edu_enrollees.csv',
 'elec_load_2017_7d.csv',
 'iris.csv',
 'iris_missing.csv',
 'krx_202105_cp949.csv',
 'krx_202105_utf8.csv',
 'linear_regression_01.csv',
 'logistic_regression_01.csv',
 'old_ver.ipynb',
 'Untitled.ipynb']

In [3]:
import pandas as pd

In [5]:
df = pd.DataFrame(dict(v1 = [100, 200, 300],
                       shape = ["a", "b", "c"],
                       v3 = ["aaa", "bbb", "abc"]))
df

v1 shape   v3
0  100     a  aaa
1  200     b  bbb
2  300     c  abc

In [8]:
df.v1

0    100
1    200
2    300
Name: v1, dtype: int64

In [6]:
df.shape

(3, 3)

In [7]:
df["shape"]

0    a
1    b
2    c
Name: shape, dtype: object

In [9]:
df.abc = 123

In [10]:
df.abc

123

In [11]:
df["abc"] = 999
df

v1 shape   v3  abc
0  100     a  aaa  999
1  200     b  bbb  999
2  300     c  abc  999

In [12]:
df.abc

123

In [15]:
df.iloc[:2, ]

v1 shape   v3  abc
0  100     a  aaa  999
1  200     b  bbb  999

In [16]:
df.loc[:2, ]

v1 shape   v3  abc
0  100     a  aaa  999
1  200     b  bbb  999
2  300     c  abc  999

In [18]:
df.columns = df.columns.str.upper()
df

V1 SHAPE   V3  ABC
0  100     a  aaa  999
1  200     b  bbb  999
2  300     c  abc  999

In [19]:
df.columns = df.columns.str.lower()
df

v1 shape   v3  abc
0  100     a  aaa  999
1  200     b  bbb  999
2  300     c  abc  999

In [20]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

지수명        종가     대비   등락률        시가        고가        저가        거래량   
0  KRX 300   1901.05 -11.63 -0.61   1913.15   1929.94   1896.65  279548840  \
1  KTOP 30  11520.28 -86.30 -0.74  11609.44  11702.14  11490.84   50048566   

             거래대금            상장시가총액        날짜  
0  13488481375036  2028800954161500  20210503  
1   5645660149606  1208343758559140  20210503

In [22]:
df_sub = df.loc[df["지수명"] == "KRX300", ]
df_sub.head(1)

Empty DataFrame
Columns: [지수명, 종가, 대비, 등락률, 시가, 고가, 저가, 거래량, 거래대금, 상장시가총액, 날짜]
Index: []

In [24]:
df["지수명"].unique()

array(['KRX 300', 'KTOP 30', 'KRX 100', 'KRX Mid 200', 'KRX 자동차',
       'KRX 반도체', 'KRX 헬스케어', 'KRX 은행', 'KRX 에너지화학', 'KRX 철강', 'KRX 방송통신',
       'KRX 건설', 'KRX 증권', 'KRX 기계장비', 'KRX 보험', 'KRX 운송', 'KRX 경기소비재',
       'KRX 필수소비재', 'KRX 미디어&엔터테인먼트', 'KRX 정보기술', 'KRX 유틸리티',
       'KRX 300 정보기술', 'KRX 300 금융', 'KRX 300 자유소비재', 'KRX 300 산업재',
       'KRX 300 헬스케어', 'KRX 300 커뮤니케이션서비스', 'KRX 300 소재', 'KRX 300 필수소비재'],
      dtype=object)

In [ ]:
df_sub = df.loc[df["지수명"] == "KRX 300"]
df_sub.head(1)

In [21]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub.head(1)

지수명       종가     대비   등락률       시가       고가       저가        거래량   
0  KRX 300  1901.05 -11.63 -0.61  1913.15  1929.94  1896.65  279548840  \

             거래대금            상장시가총액        날짜  
0  13488481375036  2028800954161500  20210503

In [25]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

지수명        종가        날짜
117  KTOP 30  11869.29  20210510

In [27]:
df["종가"].idxmax() # 최대값의 index

117

In [26]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

지수명     KTOP 30
종가     11869.29
날짜     20210510
Name: 117, dtype: object

In [28]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

지수명        종가        날짜
117  KTOP 30  11869.29  20210510

#### 자동완성

In [ ]:
# df.loc[:, "지"] # xxx
# df.loc[~~~, ["지수명", "종가", "날짜"]]
# pd.S # 대소문자를 정확하게 쓰면서 시작해야됨.
# df = pd.read_csv("classification_data_01.csv")

In [30]:
df.loc[:3, ["지수명", "종가", "날짜"]].s

(4, 3)

In [34]:
# pd.DataFrame.sh
# dir(pd.DataFrame)
ser_dir = pd.Series(dir(pd.DataFrame))
ser_dir[ser_dir.str.contains("index")]

124       _ensure_valid_index
125         _find_valid_index
136      _get_index_resolvers
146             _indexed_same
174      _needs_reindex_multi
178             _reindex_axes
179          _reindex_columns
180            _reindex_index
181            _reindex_multi
182    _reindex_with_indexers
281         first_valid_index
296                     index
313          last_valid_index
351                   reindex
352              reindex_like
358               reset_index
372                 set_index
377                sort_index
dtype: object

In [36]:
# from sklearn.m
# from sklearn.metrics import a
import sklearn.metrics as skm
ser_dir = pd.Series(dir(skm))
ser_dir[ser_dir.str.contains("score")]

25                                  _scorer
26                           accuracy_score
27               adjusted_mutual_info_score
28                      adjusted_rand_score
30                  average_precision_score
31                  balanced_accuracy_score
32                         brier_score_loss
33                  calinski_harabasz_score
38                        cohen_kappa_score
39                       completeness_score
41                          consensus_score
43                  d2_absolute_error_score
44                         d2_pinball_score
45                         d2_tweedie_score
46                     davies_bouldin_score
47                                dcg_score
50                 explained_variance_score
51                                 f1_score
52                              fbeta_score
53                    fowlkes_mallows_score
54                               get_scorer
55                         get_scorer_names
59                        homoge

In [37]:
from sklearn.metrics import accuracy_score

In [38]:
?accuracy_score

In [42]:
ser = pd.Series([9, 8, 7])
?ser.sum

In [ ]:
ser.sum()

In [43]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [46]:
df_sub["Sepal.Width"].isna()

0     True
1    False
2    False
3    False
4    False
Name: Sepal.Width, dtype: bool

In [48]:
# df_sub["Sepal.Width"].isna() == False
~df_sub["Sepal.Width"].isna()

0    False
1     True
2     True
3     True
4     True
Name: Sepal.Width, dtype: bool

In [50]:
df_sub["Sepal.Width"].count()

4

In [52]:
?pd.Series.count

In [44]:
df_sub["Sepal.Width"].isna().sum()

1

In [45]:
df_sub.isna().sum()

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [53]:
df_sub.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  5 non-null      float64
 1   Sepal.Width   4 non-null      float64
 2   Petal.Length  4 non-null      float64
 3   Petal.Width   5 non-null      float64
 4   Species       5 non-null      object 
dtypes: float64(4), object(1)
memory usage: 328.0+ bytes


In [54]:
df_sub.count()

Sepal.Length    5
Sepal.Width     4
Petal.Length    4
Petal.Width     5
Species         5
dtype: int64

In [ ]:
df_sub["Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Petal.Length"] = df_sub["Petal.Length"].fillna(df_sub["Petal.Length"].mean())

In [56]:
df_sub

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1       -999.0           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [57]:
df.isna().sum()

Sepal.Length     7
Sepal.Width     13
Petal.Length    14
Petal.Width      6
Species          0
dtype: int64

In [58]:
df_sub2 = df.loc[df["Petal.Length"].isna(), ]
df_sub2

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
0             5.1          NaN           NaN          0.2      setosa
6             NaN          NaN           NaN          NaN      setosa
7             5.0          3.4           NaN          0.2      setosa
9             4.9          3.1           NaN          0.1      setosa
10            5.4          3.7           NaN          0.2      setosa
39            5.1          NaN           NaN          0.2      setosa
42            NaN          3.2           NaN          0.2      setosa
83            6.0          2.7           NaN          1.6  versicolor
92            5.8          2.6           NaN          NaN  versicolor
103           6.3          NaN           NaN          1.8   virginica
111           NaN          NaN           NaN          NaN   virginica
138           6.0          3.0           NaN          1.8   virginica
139           6.9          NaN           NaN          2.1   virginica
146           NaN          2.5           NaN          NaN   virginica

In [60]:
df.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [63]:
df["ma3"] = df["Sepal.Length"].rolling(window = 3).mean()
df["ma_s1"] = df["ma3"].shift(1)
df["ma_sn3"] = df["ma3"].shift(-3)

In [64]:
df.head(10)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species       ma3   
0           5.1          NaN           NaN          0.2  setosa       NaN  \
1           4.9          3.0           1.4          0.2  setosa       NaN   
2           4.7          3.2           1.3          0.2  setosa  4.900000   
3           4.6          3.1           1.5          0.2  setosa  4.733333   
4           5.0          3.6           1.4          0.2  setosa  4.766667   
5           5.4          3.9           1.7          0.4  setosa  5.000000   
6           NaN          NaN           NaN          NaN  setosa       NaN   
7           5.0          3.4           NaN          0.2  setosa       NaN   
8           4.4          2.9           1.4          0.2  setosa       NaN   
9           4.9          3.1           NaN          0.1  setosa  4.766667   

      ma_s1    ma_sn3  
0       NaN  4.733333  
1       NaN  4.766667  
2       NaN  5.000000  
3  4.900000       NaN  
4  4.733333       NaN  
5  4.766667       NaN  
6  5.000000  4.766667  
7       NaN  4.900000  
8       NaN  5.033333  
9       NaN  5.000000

In [65]:
df_dropna = df.dropna()
df_dropna.isna().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
ma3             0
ma_s1           0
ma_sn3          0
dtype: int64

In [66]:
df = pd.read_csv("bike.csv")
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp   
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395  \
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [67]:
df2 = df.iloc[:, [9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11]]
df2.head(1)

casual             datetime  season  holiday  workingday  weather  temp   
0       3  2011-01-01 00:00:00       1        0           0        1  9.84  \

    atemp  humidity  windspeed  registered  count  
0  14.395        81        0.0          13     16

In [68]:
import numpy as np
df2 = df.iloc[:, np.r_[9, 0:8, 10, 11]]
df2.head(1)

casual             datetime  season  holiday  workingday  weather  temp   
0       3  2011-01-01 00:00:00       1        0           0        1  9.84  \

    atemp  humidity  registered  count  
0  14.395        81          13     16

In [69]:
df2 = df.set_index("casual").reset_index()
df2.head(2)

casual             datetime  season  holiday  workingday  weather  temp   
0       3  2011-01-01 00:00:00       1        0           0        1  9.84  \
1       8  2011-01-01 01:00:00       1        0           0        1  9.02   

    atemp  humidity  windspeed  registered  count  
0  14.395        81        0.0          13     16  
1  13.635        80        0.0          32     40

In [70]:
df2.dtypes

casual          int64
datetime       object
season          int64
holiday         int64
workingday      int64
weather         int64
temp          float64
atemp         float64
humidity        int64
windspeed     float64
registered      int64
count           int64
dtype: object

In [71]:
df = pd.read_csv("bike.csv")
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp   
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395  \
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [73]:
df_nums = df.select_dtypes(include = "number")
df_objs = df.select_dtypes(exclude = "number")

In [74]:
df_nums.head(1)

season  holiday  workingday  weather  temp   atemp  humidity  windspeed   
0       1        0           0        1  9.84  14.395        81        0.0  \

   casual  registered  count  
0       3          13     16

In [75]:
df_objs.head(1)

datetime
0  2011-01-01 00:00:00

In [76]:
df["season"].unique()

array([1, 2, 3, 4], dtype=int64)

In [78]:
df["season"].value_counts()

season
4    2734
2    2733
3    2733
1    2686
Name: count, dtype: int64

In [79]:
df["season"].value_counts(normalize = True)

season
4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: proportion, dtype: float64

In [80]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season           
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [81]:
sum((df["season"] == 1) & (df["holiday"] == 0))

2615

In [ ]:
df.loc[(df["season"] == 1) & (df["holiday"] == 0), "casual"].mean()

In [77]:
pd.crosstab(df["season"], df["holiday"], values = df["casual"],
            aggfunc = "mean")

holiday          0          1
season                       
1        15.689101   8.140845
2        47.609683  38.333333
3        50.773606  91.958333
4        28.133055  40.885417

In [84]:
df.pivot_table(index = "season", columns = "holiday", 
               values = "casual", aggfunc = "mean")

holiday          0          1
season                       
1        15.689101   8.140845
2        47.609683  38.333333
3        50.773606  91.958333
4        28.133055  40.885417

In [86]:
df.groupby(["season", "holiday"])["casual"].mean().reset_index()

season  holiday     casual
0       1        0  15.689101
1       1        1   8.140845
2       2        0  47.609683
3       2        1  38.333333
4       3        0  50.773606
5       3        1  91.958333
6       4        0  28.133055
7       4        1  40.885417

In [87]:
df["season"].nunique()

4

In [92]:
df.groupby("season")["casual", "registered"].mean()

ValueError: Cannot subset columns with a tuple with more than one element. Use a list instead.

In [90]:
df.groupby("season")[["casual", "registered"]].mean()

In [91]:
df.groupby("season")[["casual", "registered"]].agg(lambda x: round(x.mean(), 1))

casual  registered
season                    
1         15.5       100.9
2         47.4       167.8
3         52.2       182.2
4         28.6       170.4

In [94]:
x = df.loc[df["season"] == 1, "casual"]
round(x.mean(), 1)

15.5

In [95]:
df_sub = df[["season", "casual"]].copy()
df_sub.head(2)

season  casual
0       1       3
1       1       8

In [96]:
df_sub["is_season_2_1"] = np.where(df_sub["season"] == 2, 1, 0)
df_sub["is_season_2_2"] = (df_sub["season"] == 2).astype("int")
df_sub["is_season_2_3"] = (df_sub["season"] == 2) + 0
df_sub["is_season_2_4"] = (df_sub["season"] == 2) * 1
df_sub.head(2)

season  casual  is_season_2_1  is_season_2_2  is_season_2_3  is_season_2_4
0       1       3              0              0              0              0
1       1       8              0              0              0              0

In [97]:
pd.crosstab(df_sub["season"], df_sub["is_season_2_1"])

is_season_2_1     0     1
season                   
1              2686     0
2                 0  2733
3              2733     0
4              2734     0

In [100]:
df = pd.DataFrame(dict(v1 = [100, 200, 300],
                       shape = ["a", "b", "c"],
                       v3 = ["aaa", "bbb", "abc"]))
df

v1 shape   v3
0  100     a  aaa
1  200     b  bbb
2  300     c  abc

In [113]:
df["shape"].replace("a", "@@")

0    @@
1     b
2     c
Name: shape, dtype: object

In [115]:
# df["shape"].replace({"a": "@@"})
df["shape"].replace({"a": "@@", "b": "ㅋㅋㅋ"})

0     @@
1    ㅋㅋㅋ
2      c
Name: shape, dtype: object

In [118]:
df["v3"].replace("a", "@@")

0    aaa
1    bbb
2    abc
Name: v3, dtype: object

In [119]:
df["v3"].str.replace(pat = "a", repl = "@@")

0    @@@@@@
1       bbb
2      @@bc
Name: v3, dtype: object

In [120]:
df["v3"].str.replace(pat = "a", repl = "")

0       
1    bbb
2     bc
Name: v3, dtype: object

In [117]:
df

v1 shape   v3
0  100     a  aaa
1  200     b  bbb
2  300     c  abc

In [121]:
df.loc[df["v3"].str.contains("b"), ]

v1 shape   v3
1  200     b  bbb
2  300     c  abc

In [122]:
df.loc[df["v3"].str.contains("b$"), ] # 정규표현식: b로 끝나는

v1 shape   v3
1  200     b  bbb

In [124]:
ser = pd.Series(["123", "123-456", "123-456-789"])
ser.str.split("-")

0              [123]
1         [123, 456]
2    [123, 456, 789]
dtype: object

In [125]:
df_split = ser.str.split("-", expand = True)
df_split

0     1     2
0  123  None  None
1  123   456  None
2  123   456   789

In [126]:
df_split.isna().sum()

0    0
1    1
2    2
dtype: int64

In [132]:
df_split.isna().sum(axis = 1)

0    2
1    1
2    0
dtype: int64

In [128]:
df_split.fillna("")

0    1    2
0  123          
1  123  456     
2  123  456  789

In [131]:
ser = pd.Series(["123", "123-456", "123-456-789"])
df_s = ser.str.split("-").reset_index()
df_s.columns = ["v1", "v2"]
df_s.explode(column = "v2")

v1   v2
0   0  123
1   1  123
1   1  456
2   2  123
2   2  456
2   2  789

In [137]:
df_bike = pd.read_csv("bike.csv")
df_bike = df_bike[["datetime"]]
df_bike.head(2)

datetime
0  2011-01-01 00:00:00
1  2011-01-01 01:00:00

In [134]:
df_bike.dtypes

datetime    object
dtype: object

In [142]:
df_bike["dt"] = pd.to_datetime(df_bike["datetime"])
df_bike["year" ] = df_bike["dt"].dt.year 
df_bike["month"] = df_bike["dt"].dt.month
df_bike["hour" ] = df_bike["dt"].dt.hour
df_bike["wday" ] = df_bike["dt"].dt.weekday
df_bike["is_wend"] = (df_bike["wday"] >= 5) + 0

In [143]:
df_bike.head(2)

datetime                  dt  year  month  hour  wday  is_wend
0  2011-01-01 00:00:00 2011-01-01 00:00:00  2011      1     0     5        1
1  2011-01-01 01:00:00 2011-01-01 01:00:00  2011      1     1     5        1

In [144]:
pd.to_datetime([1, 2], origin = "2023-04-19", unit = "D")

DatetimeIndex(['2023-04-20', '2023-04-21'], dtype='datetime64[ns]', freq=None)

In [147]:
pd.to_datetime([100000, 200000], origin = "2023-04-19", unit = "ms")

DatetimeIndex(['2023-04-19 00:01:40', '2023-04-19 00:03:20'], dtype='datetime64[ns]', freq=None)

In [148]:
df_elec = pd.read_csv("elec_load_2017_7d.csv")
df_elec.head(1)

YEAR  MONTH  DAY   X1HR   X2HR   X3HR   X4HR   X5HR   X6HR   X7HR  ...   
0  2017      1    1  60178  57862  56165  55135  54450  54401  54147  ...  \

   X15HR  X16HR  X17HR  X18HR  X19HR  X20HR  X21HR  X22HR  X23HR  X24HR  
0  49213  49357  50362  53115  55205  55437  55348  55790  58195  59330  

[1 rows x 27 columns]

In [149]:
df_elec_melt = df_elec.melt(id_vars = ["YEAR", "MONTH", "DAY"],
                            var_name = "HOUR", value_name = "LOAD")
df_elec_melt.head(3)

YEAR  MONTH  DAY  HOUR   LOAD
0  2017      1    1  X1HR  60178
1  2017      1    2  X1HR  57067
2  2017      1    3  X1HR  66263

In [152]:
df_elec_melt["HOUR"] = df_elec_melt["HOUR"].str.replace(pat = "X|HR", repl = "",
                                                        regex = True)
df_elec_melt.dtypes

In [153]:
df_elec_melt["HOUR"] = df_elec_melt["HOUR"].astype("int")
df_elec_melt.dtypes

YEAR     int64
MONTH    int64
DAY      int64
HOUR     int32
LOAD     int64
dtype: object

In [157]:
ser_m = pd.Series([2, 4, 3, 1], 
                  index = pd.date_range("2000-01-01", periods = 4, freq = "M"))
df_m = ser_m.reset_index()
df_m["v_s1"] = df_m[0].shift(1)
df_m

index  0  v_s1
0 2000-01-31  2   NaN
1 2000-02-29  4   2.0
2 2000-03-31  3   4.0
3 2000-04-30  1   3.0

Changed the `freq` (frequency) to ``'M'`` (month end frequency).

In [163]:
pd.date_range("2000-01-31", periods = 4, freq = "D")

DatetimeIndex(['2000-01-31', '2000-02-01', '2000-02-02', '2000-02-03'], dtype='datetime64[ns]', freq='D')

In [167]:
pd.date_range("2000-12-31", periods = 4, freq = "M") + pd.to_timedelta(1, unit = "D")

DatetimeIndex(['2001-01-01', '2001-02-01', '2001-03-01', '2001-04-01'], dtype='datetime64[ns]', freq=None)

In [ ]:
pd.date_range("2000-01-31", periods = 4, freq = "D")

In [170]:
pd.date_range("2000-12-31", periods = 4, freq = "MS")

DatetimeIndex(['2001-01-01', '2001-02-01', '2001-03-01', '2001-04-01'], dtype='datetime64[ns]', freq='MS')

In [172]:
df = pd.read_csv("bike.csv")
df_1 = df.head(2)
df_2 = df.tail(2)

In [173]:
pd.concat([df_1, df_2], axis = 1)

datetime  season  holiday  workingday weather  temp   atemp   
0      2011-01-01 00:00:00     1.0      0.0         0.0     1.0  9.84  14.395  \
1      2011-01-01 01:00:00     1.0      0.0         0.0     1.0  9.02  13.635   
10884                  NaN     NaN      NaN         NaN     NaN   NaN     NaN   
10885                  NaN     NaN      NaN         NaN     NaN   NaN     NaN   

       humidity  windspeed  casual  ...  holiday  workingday weather   temp   
0          81.0        0.0     3.0  ...      NaN         NaN     NaN    NaN  \
1          80.0        0.0     8.0  ...      NaN         NaN     NaN    NaN   
10884       NaN        NaN     NaN  ...      0.0         1.0     1.0  13.94   
10885       NaN        NaN     NaN  ...      0.0         1.0     1.0  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0         NaN       NaN        NaN     NaN         NaN    NaN  
1         NaN       NaN        NaN     NaN         NaN    NaN  
10884  17.425      61.0     6.0032    12.0       117.0  129.0  
10885  16.665      66.0     8.9981     4.0        84.0   88.0  

[4 rows x 24 columns]

In [174]:
pd.concat([df_1, df_2.reset_index(drop = True)], axis = 1)

datetime  season  holiday  workingday weather  temp   atemp   
0  2011-01-01 00:00:00       1        0           0       1  9.84  14.395  \
1  2011-01-01 01:00:00       1        0           0       1  9.02  13.635   

   humidity  windspeed  casual  ...  holiday  workingday weather   temp   
0        81        0.0       3  ...        0           1       1  13.94  \
1        80        0.0       8  ...        0           1       1  13.12   

    atemp  humidity  windspeed  casual  registered  count  
0  17.425        61     6.0032      12         117    129  
1  16.665        66     8.9981       4          84     88  

[2 rows x 24 columns]

In [ ]:
# df = pd.read_csv("bike.csv")

In [175]:
df2 = df[["datetime", "temp"]].copy()
df2["datetime"] = pd.to_datetime(df2["datetime"])
df2["date"] = df2["datetime"].dt.date
df2.head(2)

In [180]:
df2_agg = df2.groupby("date")["temp"].max().reset_index()

df2_join = df2.merge(df2_agg, on = "date")
df2_join.head(2)

datetime  temp_x        date  temp_y
0 2011-01-01 00:00:00    9.84  2011-01-01   18.86
1 2011-01-01 01:00:00    9.02  2011-01-01   18.86

In [179]:
df2_agg = df2.groupby("date")["temp"].max().reset_index()
df2_agg = df2_agg.rename(columns = {"temp": "temp_max"})

df2_join = df2.merge(df2_agg, on = "date")
df2_join.head(2)

datetime  temp        date  temp_max
0 2011-01-01 00:00:00  9.84  2011-01-01     18.86
1 2011-01-01 01:00:00  9.02  2011-01-01     18.86

In [181]:
ser_m = pd.Series(["123원", "1.23$", "1,345$"])
ser_m

0      123원
1     1.23$
2    1,345$
dtype: object

In [ ]:
ser_m.str.replace("원", "")

In [184]:
# ser_m.str.replace("원|$", "", regex = True)
# ser_m.str.replace("원|\$", "", regex = True)
ser_m.str.replace("원|\$|,", "", regex = True)

0     123
1    1.23
2    1345
dtype: object

In [185]:
ser_m.str.replace("[^0-9.]", "", regex = True)

0     123
1    1.23
2    1345
dtype: object

In [188]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [187]:
df_iris = pd.read_csv("iris.csv")
df_iris.head(1)

SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa

In [191]:
model = KMeans(n_clusters = 3, random_state = 123)
model.fit(X = df_iris.drop(columns = "Species"))

In [192]:
silhouette_score(df_iris.drop(columns = "Species"), 
                 labels = model.labels_)

0.5528190123564102

In [194]:
pd.DataFrame(model.cluster_centers_, 
             columns = df_iris.columns[:-1])

SepalLength  SepalWidth  PetalLength  PetalWidth
0     6.850000    3.073684     5.742105    2.071053
1     5.006000    3.428000     1.462000    0.246000
2     5.901613    2.748387     4.393548    1.433871

In [196]:
model.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2])

In [195]:
pd.Series(model.labels_).value_counts()

2    62
1    50
0    38
Name: count, dtype: int64

In [197]:
df_dia = pd.read_csv("diamonds.csv")
df_dia.head(2)

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [198]:
df_dia["cut"].unique()

array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object)

In [200]:
# df_dia[["cut", "color"]].unique()

In [201]:
df_dia[["cut", "color"]].drop_duplicates()

cut color
0        Ideal     E
1      Premium     E
2         Good     E
3      Premium     I
4         Good     J
5    Very Good     J
6    Very Good     I
7    Very Good     H
8         Fair     E
11       Ideal     J
12     Premium     F
16       Ideal     I
20        Good     I
21   Very Good     E
25   Very Good     G
28   Very Good     D
29   Very Good     F
35        Good     F
37        Good     H
42        Good     D
51       Ideal     G
54     Premium     D
56     Premium     J
62       Ideal     D
68     Premium     G
72     Premium     H
97        Fair     F
108      Ideal     F
128       Fair     H
130      Ideal     H
184       Good     G
227       Fair     G
255       Fair     J
352       Fair     I
676       Fair     D

In [202]:
df_dia[["cut", "color"]].apply(lambda x: x.unique())

cut      [Ideal, Premium, Good, Very Good, Fair]
color                      [E, I, J, H, F, G, D]
dtype: object

In [203]:
df_dia[["cut", "color"]].nunique()

cut      5
color    7
dtype: int64

In [212]:
df_dia = pd.read_csv("diamonds.csv")
df_dia_num = df_dia.select_dtypes(include = "number")
df_dia_num = df_dia_num.set_index("price").reset_index()

In [206]:
from sklearn.model_selection import train_test_split

In [208]:
df_train, df_test = train_test_split(df_dia_num, train_size = 0.7, 
                                     random_state = 123)
len(df_train), len(df_test)

(37758, 16182)

In [210]:
from sklearn.preprocessing import StandardScaler
model_nor = StandardScaler().fit(df_train)
arr_train_nor = model_nor.transform(df_train)
arr_test_nor  = model_nor.transform(df_test)

In [211]:
arr_train_nor[:2, ]

array([[ 0.43363556,  0.55116139, -0.87705508, -0.20503673,  0.79886224,
         0.74694202,  0.64630735],
       [-0.73466162, -0.84330851,  0.31649342, -1.10028304, -0.87788733,
        -0.83947701, -0.81830926]])

In [214]:
model_nor.mean_ # train set의 각 변수별 평균

array([3.94046650e+03, 7.99136342e-01, 6.17492108e+01, 5.74580566e+01,
       5.73430213e+00, 5.73837147e+00, 3.54106785e+00])

In [215]:
model_nor.scale_ # train set의 각 변수별 표준편차

array([3.98614333e+03, 4.73298132e-01, 1.42432419e+00, 2.23402205e+00,
       1.12121693e+00, 1.15354138e+00, 7.10083442e-01])

In [219]:
df_test.head(1)

price  carat  depth  table     x     y     z
32685    802   0.31   63.0   57.0  4.32  4.28  2.71

In [222]:
StandardScaler().fit_transform(df_test.head(2))

array([[-1., -1.,  1.,  1., -1., -1., -1.],
       [ 1.,  1., -1., -1.,  1.,  1.,  1.]])