In [ ]:
import os
os.listdir()

### - 변수명을 attb와 동일하게 사용하면 헷갈리니, 그냥 ["column이름"] 으로 사용하자
### - iloc는 개수로 나오니 헷갈리지 말자

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(dict(v1 = [100, 200, 300],
                       shape = ["a", "b", "c"],
                       v3 = ["aaa", "bbb", "ccc"]))
df

In [ ]:
df.v1

In [ ]:
df.shape

In [ ]:
df["shape"]

In [ ]:
df.iloc[:2, ]

In [ ]:
df.loc[:2, ]

In [ ]:
df.columns

In [ ]:
df.columns = df.columns.str.upper()
df

In [ ]:
df.columns = df.columns.str.lower()
df

In [ ]:
df = pd.read_csv("krx_202105_utf8.csv")
df.head(2)

### - 지수명에 'KRX300' 인지 'KRX 300'인지 띄어쓰기 알 수 없음. 항상 데이터 head()로 조회해라

In [ ]:
df_sub = df.loc[df["지수명"] == "KRX 300", ]
df_sub.head(1)

In [ ]:
df_sub = df.loc[df["지수명"] == "KRX300", ]
df_sub.head(1)

### - 또는 unique()로 칼럼이름을 조회해라

In [ ]:
df["지수명"].unique()

### - 최대값 찾기 문제 : 같은 값이 있을 수 있기 때문에 조심

In [ ]:
df.loc[df["종가"] == df["종가"].max(), ["지수명", "종가", "날짜"]]

In [ ]:
df["종가"].idxmax()

In [ ]:
df.loc[df["종가"].idxmax(), ["지수명", "종가", "날짜"]]

In [ ]:
df.loc[[df["종가"].idxmax()], ["지수명", "종가", "날짜"]]

### - 자동완성

In [ ]:
df["지수명"]   # tab을 활용하자

pd.S   # 대소문자를 조심하자

df = pd.read_csv("classification_data_01.csv")   # 따옴표 안에서 tab을 누르면 파일리스트 뜬다

# tab을 사용해서 호출하고 싶을 때는, 간단 코드를 써서 활용하자
pd.DataFrame.shape

In [ ]:
dir(pd.DataFrame)   # 전체 리스트 확인은 가능함

In [ ]:
ser_dir = pd.Series(dir(pd.DataFrame))
ser_dir[ser_dir.str.contains("index")]

In [5]:
pip install "scikit-learn"

     ---------------------------------------- 8.4/8.4 MB 19.8 MB/s eta 0:00:00
     ---------------------------------------- 298.0/298.0 kB ? eta 0:00:00
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
Note: you may need to restart the kernel to use updated packages.


In [7]:
#from sklearn.metrics import accuracy_scor
import sklearn.metrics as skm
dir(skm)

['ConfusionMatrixDisplay',
 'DetCurveDisplay',
 'DistanceMetric',
 'PrecisionRecallDisplay',
 'PredictionErrorDisplay',
 'RocCurveDisplay',
 'SCORERS',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_classification',
 '_dist_metrics',
 '_pairwise_distances_reduction',
 '_pairwise_fast',
 '_plot',
 '_ranking',
 '_regression',
 '_scorer',
 'accuracy_score',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'auc',
 'average_precision_score',
 'balanced_accuracy_score',
 'brier_score_loss',
 'calinski_harabasz_score',
 'check_scoring',
 'class_likelihood_ratios',
 'classification_report',
 'cluster',
 'cohen_kappa_score',
 'completeness_score',
 'confusion_matrix',
 'consensus_score',
 'coverage_error',
 'd2_absolute_error_score',
 'd2_pinball_score',
 'd2_tweedie_score',
 'davies_bouldin_score',
 'dcg_score',
 'det_curve',
 'euclidean_distances',
 'explained_variance_score',
 'f1_

In [8]:
from sklearn.metrics import accuracy_score

In [9]:
?accuracy_score

In [ ]:
# shift + tab + tab 기능 활용

In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("iris_missing.csv")
df_sub = df.head()
df_sub

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
~df_sub["Sepal.Width"].isna()

0    False
1     True
2     True
3     True
4     True
Name: Sepal.Width, dtype: bool

In [19]:
df_sub["Sepal.Width"].isna()

0     True
1    False
2    False
3    False
4    False
Name: Sepal.Width, dtype: bool

### 결측 개수 세기

In [22]:
print(df_sub["Sepal.Width"].isna().sum())   # isna()를 하면 True, False로 되어서 count는 전체가됨.
print(df_sub["Sepal.Width"].isna().count())

1
5


5

In [16]:
df_sub.isna().sum()

Sepal.Length    0
Sepal.Width     1
Petal.Length    1
Petal.Width     0
Species         0
dtype: int64

In [20]:
df_sub["Sepal.Width"].count()

4

In [23]:
df_sub.count()

Sepal.Length    5
Sepal.Width     4
Petal.Length    4
Petal.Width     5
Species         5
dtype: int64

### 결측 채우기

In [24]:
df_sub["Sepal.Width"] = df_sub["Sepal.Width"].fillna(-999)
df_sub["Sepal.Length"] = df_sub["Sepal.Length"].fillna(df_sub["Petal.Length"].mean()

SyntaxError: unexpected EOF while parsing (1967897951.py, line 2)

In [25]:
df_sub

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [27]:
df_sub2 = df.loc[df["Petal.Length"].isna(), ]
df_sub2

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
0             5.1          NaN           NaN          0.2      setosa
6             NaN          NaN           NaN          NaN      setosa
7             5.0          3.4           NaN          0.2      setosa
9             4.9          3.1           NaN          0.1      setosa
10            5.4          3.7           NaN          0.2      setosa
39            5.1          NaN           NaN          0.2      setosa
42            NaN          3.2           NaN          0.2      setosa
83            6.0          2.7           NaN          1.6  versicolor
92            5.8          2.6           NaN          NaN  versicolor
103           6.3          NaN           NaN          1.8   virginica
111           NaN          NaN           NaN          NaN   virginica
138           6.0          3.0           NaN          1.8   virginica
139           6.9          NaN           NaN          2.1   virginica
146           NaN          2.5           NaN          NaN   virginica

### dropna

In [28]:
df_dropna = df.dropna()
df_dropna.isna().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

### shift 시켜보기

In [29]:
df["ma3"] = df["Sepal.Length"].rolling(window = 3).mean()
df["ma_s1"] = df["ma3"].shift(1)
df["ma_s2"] = df["ma3"].shift(-3)

In [31]:
df.head(10)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species       ma3  \
0           5.1          NaN           NaN          0.2  setosa       NaN   
1           4.9          3.0           1.4          0.2  setosa       NaN   
2           4.7          3.2           1.3          0.2  setosa  4.900000   
3           4.6          3.1           1.5          0.2  setosa  4.733333   
4           5.0          3.6           1.4          0.2  setosa  4.766667   
5           5.4          3.9           1.7          0.4  setosa  5.000000   
6           NaN          NaN           NaN          NaN  setosa       NaN   
7           5.0          3.4           NaN          0.2  setosa       NaN   
8           4.4          2.9           1.4          0.2  setosa       NaN   
9           4.9          3.1           NaN          0.1  setosa  4.766667   

      ma_s1     ma_s2  
0       NaN  4.733333  
1       NaN  4.766667  
2       NaN  5.000000  
3  4.900000       NaN  
4  4.733333       NaN  
5  4.766667       NaN  
6  5.000000  4.766667  
7       NaN  4.900000  
8       NaN  5.033333  
9       NaN  5.000000

###...

In [32]:
df = pd.read_csv("bike.csv")
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [33]:
df2 =df.iloc[:, [9,0,1,2,3,4,5,6,7,8,10,11]]
df2.head(1)

casual             datetime  season  holiday  workingday  weather  temp  \
0       3  2011-01-01 00:00:00       1        0           0        1  9.84   

    atemp  humidity  windspeed  registered  count  
0  14.395        81        0.0          13     16

In [34]:
import numpy as np
df2 = df.iloc[:, np.r_[9, 0:8, 10,11]]
df2.head(1)

casual             datetime  season  holiday  workingday  weather  temp  \
0       3  2011-01-01 00:00:00       1        0           0        1  9.84   

    atemp  humidity  registered  count  
0  14.395        81          13     16

In [35]:
df2 = df.set_index("casual").reset_index()   # 종속변수를 맨 앞으로 위치시킴
df2.head(2)

casual             datetime  season  holiday  workingday  weather  temp  \
0       3  2011-01-01 00:00:00       1        0           0        1  9.84   
1       8  2011-01-01 01:00:00       1        0           0        1  9.02   

    atemp  humidity  windspeed  registered  count  
0  14.395        81        0.0          13     16  
1  13.635        80        0.0          32     40

In [36]:
df2.dtypes

casual          int64
datetime       object
season          int64
holiday         int64
workingday      int64
weather         int64
temp          float64
atemp         float64
humidity        int64
windspeed     float64
registered      int64
count           int64
dtype: object

### 속성 확인 및 변환 꿀팁

In [37]:
df_nums = df.select_dtypes(include = 'number')
df_objs = df.select_dtypes(exclude = 'number')

In [38]:
df_nums.head(1)

season  holiday  workingday  weather  temp   atemp  humidity  windspeed  \
0       1        0           0        1  9.84  14.395        81        0.0   

   casual  registered  count  
0       3          13     16

In [39]:
df_objs.head(1)

datetime
0  2011-01-01 00:00:00

### 원소 개수 확인

In [40]:
df["season"].unique()

array([1, 2, 3, 4], dtype=int64)

In [41]:
df["season"].value_counts()

4    2734
2    2733
3    2733
1    2686
Name: season, dtype: int64

In [42]:
df["season"].value_counts(normalize = True)

4    0.251148
2    0.251056
3    0.251056
1    0.246739
Name: season, dtype: float64

In [43]:
pd.crosstab(df["season"], df["holiday"])

holiday     0   1
season           
1        2615  71
2        2685  48
3        2637  96
4        2638  96

In [46]:
sum((df["season"] == 1) & (df["holiday"] == 0))

2615

In [44]:
pd.crosstab(df["season"], df["holiday"], values = df["casual"], aggfunc = "mean")

holiday          0          1
season                       
1        15.689101   8.140845
2        47.609683  38.333333
3        50.773606  91.958333
4        28.133055  40.885417

In [47]:
df.loc[(df["season"] == 1) & (df["holiday"] == 0), "casual"].mean()

15.689101338432122

In [49]:
df.pivot_table(index = "season", columns = "holiday", values = "casual", aggfunc = "mean")

holiday          0          1
season                       
1        15.689101   8.140845
2        47.609683  38.333333
3        50.773606  91.958333
4        28.133055  40.885417

In [48]:
df.groupby(["season", "holiday"])["casual"].mean()

season  holiday
1       0          15.689101
        1           8.140845
2       0          47.609683
        1          38.333333
3       0          50.773606
        1          91.958333
4       0          28.133055
        1          40.885417
Name: casual, dtype: float64

In [50]:
df["season"].nunique()

4

In [53]:
df.groupby("season")[["casual", "registered"]].mean()

casual  registered
season                       
1       15.489576  100.853686
2       47.446762  167.804610
3       52.220271  182.196853
4       28.580834  170.407462

In [55]:
df.groupby("season")[["casual", "registered"]].agg(lambda x: round(x.mean(), 1))

casual  registered
season                    
1         15.5       100.9
2         47.4       167.8
3         52.2       182.2
4         28.6       170.4

In [56]:
x = df.loc[df["season"] == 1, "casual"]   # 위에 lambda는 이와 같이 동작한다
round(x.mean(), 1)

15.5

### 다양한 변수 생성법

In [57]:
df_sub = df[["season", "casual"]].copy()
df_sub.head(2)

season  casual
0       1       3
1       1       8

In [64]:
# 다 같은 결과임
df_sub["is_season_2_1"] = np.where(df_sub["season"] == 2,1,0)
df_sub["is_season_2_2"] = (df_sub["season"] == 2).astype("int")
df_sub["is_season_2_3"] = (df_sub["season"] == 2) + 0  # 덧셈의 항등원
df_sub["is_season_2_4"] = (df_sub["season"] == 2) * 1  # 곱셈의 항등원
#df_sub.head(10)
df_sub[df_sub["season"] == 2].head(10)

season  casual  is_season_2_1  is_season_2_2  is_season_2_3  \
1323       2       0              1              1              1   
1324       2       0              1              1              1   
1325       2       0              1              1              1   
1326       2       0              1              1              1   
1327       2       0              1              1              1   
1328       2       1              1              1              1   
1329       2       2              1              1              1   
1330       2       4              1              1              1   
1331       2       8              1              1              1   
1332       2      11              1              1              1   

      is_season_2_4  
1323              1  
1324              1  
1325              1  
1326              1  
1327              1  
1328              1  
1329              1  
1330              1  
1331              1  
1332              1

In [60]:
pd.crosstab(df_sub["season"], df_sub["is_season_2_1"])

is_season_2_1     0     1
season                   
1              2686     0
2                 0  2733
3              2733     0
4              2734     0

### str, text 처리

In [78]:
df = pd.DataFrame(dict(v1 = [100, 200, 300],
                       shape = ["a", "b", "c"],
                       v3 = ["aaa", "bbb", "abc"]))
df

v1 shape   v3
0  100     a  aaa
1  200     b  bbb
2  300     c  abc

In [79]:
df["shape"].replace("a", "@@")   # replace는 정확히 원소가 매칭이 되어야 한다

0    @@
1     b
2     c
Name: shape, dtype: object

In [80]:
df["shape"].replace({"a":"##", "b" : "ㅋㅋㅋ"})   # replace는 복수개도 한 번에 변경 가능

0     ##
1    ㅋㅋㅋ
2      c
Name: shape, dtype: object

In [81]:
df["v3"].replace("a", "@@")   # 안바뀐다...str이 별도로 필요함

0    aaa
1    bbb
2    abc
Name: v3, dtype: object

In [82]:
df["v3"].str.replace(pat = "a", repl = "@@")

0    @@@@@@
1       bbb
2      @@bc
Name: v3, dtype: object

In [83]:
df["v3"].str.replace(pat = "a", repl = "")

0       
1    bbb
2     bc
Name: v3, dtype: object

In [86]:
df.loc[df["v3"].str.contains("b"), ]   # b를 포함하고 있는 것

v1 shape   v3
1  200     b  bbb
2  300     c  abc

In [85]:
df.loc[df["v3"].str.contains("b$"), ]   # 정규표현식 : b로 끝나는것

v1 shape   v3
1  200     b  bbb

### split

In [87]:
ser = pd.Series(["123", "123-456", "123-456-789"])   # split은 가능하지만, 다루기 쉽지 않다
ser.str.split("-")

0              [123]
1         [123, 456]
2    [123, 456, 789]
dtype: object

In [88]:
df_split = ser.str.split("-", expand = True)   # expand를 사용하면 df 형태로 저정되어 관리가 편하다
df_split

0     1     2
0  123  None  None
1  123   456  None
2  123   456   789

In [89]:
df_split.isna().sum()

0    0
1    1
2    2
dtype: int64

In [90]:
df_split.fillna("")

0    1    2
0  123          
1  123  456     
2  123  456  789

In [94]:
ser = pd.Series(["123", "123-456", "123-456-789"])
df_s = ser.str.split("-").reset_index()
df_s.columns = ["v1", "v2"]
#df_s.explode(column = "v2")
df_s

v1               v2
0   0            [123]
1   1       [123, 456]
2   2  [123, 456, 789]

In [97]:
ser = pd.Series(["123", "123-456", "123-456-789"])
df_s = ser.str.split("-").reset_index()
df_s.columns = ["v1", "v2"]
df_s.explode(column = "v2")

v1   v2
0   0  123
1   1  123
1   1  456
2   2  123
2   2  456
2   2  789

### 시간 데이터 처리

In [105]:
df_bike = pd.read_csv("bike.csv")
df_bike = df_bike[["datetime"]]
df_bike.head(5)

datetime
0  2011-01-01 00:00:00
1  2011-01-01 01:00:00
2  2011-01-01 02:00:00
3  2011-01-01 03:00:00
4  2011-01-01 04:00:00

In [99]:
df_bike.dtypes

datetime    object
dtype: object

In [102]:
df_bike["dt"   ] = pd.to_datetime(df_bike["datetime"])   # to_datettime() 이 시작점
df_bike["year" ] = df_bike["dt"].dt.year
df_bike["month"] = df_bike["dt"].dt.month
df_bike["hour" ] = df_bike["dt"].dt.hour
df_bike["wday" ] = df_bike["dt"].dt.weekday
df_bike["is_wend"] = (df_bike["wday"] >= 5) + 0

In [103]:
df_bike.head(5)

datetime                  dt  year  month  hour  wday  is_wend
0  2011-01-01 00:00:00 2011-01-01 00:00:00  2011      1     0     5        1
1  2011-01-01 01:00:00 2011-01-01 01:00:00  2011      1     1     5        1
2  2011-01-01 02:00:00 2011-01-01 02:00:00  2011      1     2     5        1
3  2011-01-01 03:00:00 2011-01-01 03:00:00  2011      1     3     5        1
4  2011-01-01 04:00:00 2011-01-01 04:00:00  2011      1     4     5        1

In [106]:
pd.to_datetime([1,2], origin = "2023-04-19", unit = "D")

DatetimeIndex(['2023-04-20', '2023-04-21'], dtype='datetime64[ns]', freq=None)

In [107]:
pd.to_datetime([1,2], origin = "2023-04-19", unit = "us")

DatetimeIndex(['2023-04-19 00:00:00.000001', '2023-04-19 00:00:00.000002'], dtype='datetime64[ns]', freq=None)

In [108]:
pd.to_datetime([100000,200000], origin = "2023-04-19", unit = "ms")

DatetimeIndex(['2023-04-19 00:01:40', '2023-04-19 00:03:20'], dtype='datetime64[ns]', freq=None)

### melt

In [109]:
df_elec = pd.read_csv("elec_load_2017_7d.csv")
df_elec.head(2)

YEAR  MONTH  DAY   X1HR   X2HR   X3HR   X4HR   X5HR   X6HR   X7HR  ...  \
0  2017      1    1  60178  57862  56165  55135  54450  54401  54147  ...   
1  2017      1    2  57067  55148  53983  53571  54027  55388  57753  ...   

   X15HR  X16HR  X17HR  X18HR  X19HR  X20HR  X21HR  X22HR  X23HR  X24HR  
0  49213  49357  50362  53115  55205  55437  55348  55790  58195  59330  
1  72228  71945  72641  73387  72294  69989  67893  66504  67435  69275  

[2 rows x 27 columns]

In [110]:
df_elec_melt = df_elec.melt(id_vars= ["YEAR", "MONTH", "DAY"],
                           var_name = "HOUR", value_name = "LOAD")
df_elec_melt.head(3)

YEAR  MONTH  DAY  HOUR   LOAD
0  2017      1    1  X1HR  60178
1  2017      1    2  X1HR  57067
2  2017      1    3  X1HR  66263

In [111]:
df_elec_melt["HOUR"] = df_elec_melt["HOUR"].str.replace(pat = "X|HR", repl = "", regex = True)
df_elec_melt.dtypes

YEAR      int64
MONTH     int64
DAY       int64
HOUR     object
LOAD      int64
dtype: object

In [112]:
df_elec_melt["HOUR"] = df_elec_melt["HOUR"].astype("int")
df_elec_melt.dtypes

YEAR     int64
MONTH    int64
DAY      int64
HOUR     int32
LOAD     int64
dtype: object

In [115]:
pd.date_range("2000-01-31", periods = 4, freq = "M")

DatetimeIndex(['2000-01-31', '2000-02-29', '2000-03-31', '2000-04-30'], dtype='datetime64[ns]', freq='M')

In [116]:
pd.date_range("2000-01-31", periods = 4, freq = "MS")   # month start

DatetimeIndex(['2000-02-01', '2000-03-01', '2000-04-01', '2000-05-01'], dtype='datetime64[ns]', freq='MS')

### concat

In [118]:
df = pd.read_csv("bike.csv")
df_1 = df.head(2)
df_2 = df.tail(2)

In [122]:
pd.concat([df_1, df_2])

datetime  season  holiday  workingday  weather   temp  \
0      2011-01-01 00:00:00       1        0           0        1   9.84   
1      2011-01-01 01:00:00       1        0           0        1   9.02   
10884  2012-12-19 22:00:00       4        0           1        1  13.94   
10885  2012-12-19 23:00:00       4        0           1        1  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0      14.395        81     0.0000       3          13     16  
1      13.635        80     0.0000       8          32     40  
10884  17.425        61     6.0032      12         117    129  
10885  16.665        66     8.9981       4          84     88

In [120]:
pd.concat([df_1, df_2], axis = 1)

datetime  season  holiday  workingday weather  temp   atemp  \
0      2011-01-01 00:00:00     1.0      0.0         0.0     1.0  9.84  14.395   
1      2011-01-01 01:00:00     1.0      0.0         0.0     1.0  9.02  13.635   
10884                  NaN     NaN      NaN         NaN     NaN   NaN     NaN   
10885                  NaN     NaN      NaN         NaN     NaN   NaN     NaN   

       humidity  windspeed  casual  ...  holiday  workingday weather   temp  \
0          81.0        0.0     3.0  ...      NaN         NaN     NaN    NaN   
1          80.0        0.0     8.0  ...      NaN         NaN     NaN    NaN   
10884       NaN        NaN     NaN  ...      0.0         1.0     1.0  13.94   
10885       NaN        NaN     NaN  ...      0.0         1.0     1.0  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0         NaN       NaN        NaN     NaN         NaN    NaN  
1         NaN       NaN        NaN     NaN         NaN    NaN  
10884  17.425      61.0     6.0032    12.0       117.0  129.0  
10885  16.665      66.0     8.9981     4.0        84.0   88.0  

[4 rows x 24 columns]

In [121]:
pd.concat([df_1, df_2.reset_index(drop = True)], axis = 1)

datetime  season  holiday  workingday weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0       1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0       1  9.02  13.635   

   humidity  windspeed  casual  ...  holiday  workingday weather   temp  \
0        81        0.0       3  ...        0           1       1  13.94   
1        80        0.0       8  ...        0           1       1  13.12   

    atemp  humidity  windspeed  casual  registered  count  
0  17.425        61     6.0032      12         117    129  
1  16.665        66     8.9981       4          84     88  

[2 rows x 24 columns]

In [124]:
df2 = df[["datetime", "temp"]].copy()
df2["datetime"] = pd.to_datetime(df2["datetime"])
df2["date"] = df2["datetime"].dt.date
df2.head(2)

datetime  temp        date
0 2011-01-01 00:00:00  9.84  2011-01-01
1 2011-01-01 01:00:00  9.02  2011-01-01

In [130]:
df2_agg = df2.groupby("date")["temp"].max().reset_index()
df2_agg = df2_agg.rename(columns = {"temp": "temp_max"})
df2_agg.head()

date  temp_max
0  2011-01-01     18.86
1  2011-01-02     18.86
2  2011-01-03     10.66
3  2011-01-04     12.30
4  2011-01-05     12.30

In [127]:
df2.join = df2.merge(df2_agg, on = "date")
df2.join.head(2)

datetime  temp        date  temp_max
0 2011-01-01 00:00:00  9.84  2011-01-01     18.86
1 2011-01-01 01:00:00  9.02  2011-01-01     18.86

### 실루엣 스코어

In [131]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [132]:
df_iris = pd.read_csv("iris.csv")
df_iris.head()

SepalLength  SepalWidth  PetalLength  PetalWidth Species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [133]:
model = KMeans(n_clusters = 3, random_state = 123)
model.fit(X = df_iris.drop(columns = "Species"))

C:\Users\hyojin\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\hyojin\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=3, random_state=123)

In [134]:
silhouette_score(df_iris.drop(columns = "Species"), labels = model.labels_)

0.5528190123564101

In [136]:
model.cluster_centers_

array([[6.85      , 3.07368421, 5.74210526, 2.07105263],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.9016129 , 2.7483871 , 4.39354839, 1.43387097]])

In [137]:
pd.DataFrame(model.cluster_centers_, columns = df_iris.columns[:-1])   # Data Frame 변환이 보기 좋다

SepalLength  SepalWidth  PetalLength  PetalWidth
0     6.850000    3.073684     5.742105    2.071053
1     5.006000    3.428000     1.462000    0.246000
2     5.901613    2.748387     4.393548    1.433871

In [138]:
model.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2])

In [139]:
pd.Series(model.labels_).value_counts()

2    62
1    50
0    38
dtype: int64

In [140]:
df_dia = pd.read_csv("diamonds.csv")
df_dia.head(2)

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [141]:
df_dia["cut"].unique()

array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object)

In [143]:
df_dia[["cut", "color"]].unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [147]:
df_dia[["cut", "color"]].drop_duplicates()

cut color
0        Ideal     E
1      Premium     E
2         Good     E
3      Premium     I
4         Good     J
5    Very Good     J
6    Very Good     I
7    Very Good     H
8         Fair     E
11       Ideal     J
12     Premium     F
16       Ideal     I
20        Good     I
21   Very Good     E
25   Very Good     G
28   Very Good     D
29   Very Good     F
35        Good     F
37        Good     H
42        Good     D
51       Ideal     G
54     Premium     D
56     Premium     J
62       Ideal     D
68     Premium     G
72     Premium     H
97        Fair     F
108      Ideal     F
128       Fair     H
130      Ideal     H
184       Good     G
227       Fair     G
255       Fair     J
352       Fair     I
676       Fair     D

In [145]:
df_dia[["cut", "color"]].apply(lambda x: x.unique())

cut      [Ideal, Premium, Good, Very Good, Fair]
color                      [E, I, J, H, F, G, D]
dtype: object

In [148]:
df_dia_num = df_dia.select_dtypes(include = 'number')
df_dia_num.head(1)

carat  depth  table  price     x     y     z
0   0.23   61.5   55.0    326  3.95  3.98  2.43

In [149]:
df_dia_num = df_dia_num.set_index("price").reset_index()
df_dia_num.head(1)

price  carat  depth  table     x     y     z
0    326   0.23   61.5   55.0  3.95  3.98  2.43

In [150]:
from sklearn.model_selection import train_test_split

In [151]:
df_train, df_test = train_test_split(df_dia_num, train_size=0.7, random_state=123)
len(df_train), len(df_test)

(37758, 16182)

In [152]:
from sklearn.preprocessing import StandardScaler
model_nor = StandardScaler().fit(df_train)
arr_train_nor = model_nor.transform(df_train)
arr_test_nor  = model_nor.transform(df_test)

In [153]:
arr_train_nor[:2,]

array([[ 0.43363556,  0.55116139, -0.87705508, -0.20503673,  0.79886224,
         0.74694202,  0.64630735],
       [-0.73466162, -0.84330851,  0.31649342, -1.10028304, -0.87788733,
        -0.83947701, -0.81830926]])

In [155]:
model_nor.mean_   # train set의 각 변수별 평균

array([3.94046650e+03, 7.99136342e-01, 6.17492108e+01, 5.74580566e+01,
       5.73430213e+00, 5.73837147e+00, 3.54106785e+00])

In [156]:
model_nor.scale_   # train set의 각 변수별 표준편차

array([3.98614333e+03, 4.73298132e-01, 1.42432419e+00, 2.23402205e+00,
       1.12121693e+00, 1.15354138e+00, 7.10083442e-01])