### 라이브러리 호출
NumPy는 두 글자로 줄인 "np"로 사용

> **import** numpy **as** np

In [1]:
import numpy as np

### NumPy 객체 - Array
다차원의 복잡한 구조 구현이 가능한 객체로 리스트를 기반으로 생성하며 벡터연산과 행렬연산 뿐만아니라 다양한 수치연산까지 지원.

* 생성  
array() 함수에 리스트 객체를 입력. 객체의 차원은 리스트 객체의 중첩수와 동일하며 2차원 객체의 경우 중첩된 리스트를 쉼표를 사용하여 행을 구분함.  
2차원 배열의 경우 특정 행에 할당되는 원소의 개수 또는 특정 열 할당되는 원소의 개수가 같아야 하며 특정 위치의 원소를 명시하지 않으려면 결측 표기를 사용해야함.  
※ np.nan  
  
  
* 조작  
기본 행렬연산을 지원하며 각종 메서드를 활용하여 복잡한 산술연산 수행 가능.  
리스트 객체와는 달리 일부 원소를 추출할 때 이산 위치의 원소 또한 추출 가능.  
특정 위치의 원소를 추출하는 것 뿐만 아니라 조건식을 사용한 필터링 가능.  
일부 또는 전체를 복제하는 경우 단순 데이터의 주소만 복사하는 "얕은 복사"와 데이터를 온전히 복사하는 "깊은 복사"의 동작에 유의할 것.
※ np.array.copy()

In [ ]:
np.array([1, 2])

In [ ]:
np.array([[1, 2], [3, 4]])

In [ ]:
np.array([[1, 2], [3, 4, 5]])

In [6]:
np.array([[1, 2, np.nan], [3, 4, 5]])

array([[ 1.,  2., nan],
       [ 3.,  4.,  5.]])

In [60]:
arr1 = np.array([2, 4, 6, 8])
arr1.shape # shape는 각 차원의 길이(또는 원소 개수)

(4,)

In [61]:
arr1.sum(), arr1.std(), arr1.var(), arr1.min(), arr1.max()

(20, 2.23606797749979, 5.0, 2, 8)

In [62]:
arr1.argmax(), arr1.argmin()

(3, 0)

In [64]:
arr1 + 1000

array([1002, 1004, 1006, 1008])

In [65]:
arr1 * 20

array([ 40,  80, 120, 160])

In [14]:
arr1.reshape((2, 2)) # 2x2 배열(행렬)로 자료구조 변경

array([[2, 4],
       [6, 8]])

In [17]:
arr1[0], arr1[:2], arr1[-1], arr1[[1, 3]]

(2, array([2, 4]), 8, array([4, 8]))

In [18]:
arr1_sub = arr1[2:]
arr1_sub

array([6, 8])

In [19]:
arr1[-1] = 999
arr1_sub

array([  6, 999])

In [20]:
arr1_sub2 = arr1[:2].copy() # 깊은 복사
arr1[0] = 999
arr1_sub2

array([2, 4])

In [22]:
arr1 > 100

array([ True, False, False,  True])

In [23]:
arr1[arr1 > 100] # 조건식 결과가 True에 해당하는 위치의 원소가 필터링 됨

array([999, 999])

In [25]:
arr2 = np.array([[100, 200, 300], [400, 500, 600]])
arr2 

array([[100, 200, 300],
       [400, 500, 600]])

In [27]:
# 모든 원소를 일괄 연산
arr2.sum(), arr2.std(), arr2.var(), arr2.min(), arr2.max()

(2100, 170.78251276599332, 29166.666666666668, 100, 600)

In [30]:
arr2.sum(axis = 0), arr2.sum(axis = 1)

(array([500, 700, 900]), array([ 600, 1500]))

In [31]:
arr2.reshape((3, 2))

array([[100, 200],
       [300, 400],
       [500, 600]])

In [37]:
arr2[1] # 쉼표를 사용하지 않는 경우 row 기준 index로 동작하나 사용 지양

array([400, 500, 600])

In [38]:
arr2[1, ] # 쉼표 뒤를 생략하면 모든 column을 지정하는 것과 같다.

array([400, 500, 600])

In [40]:
# arr2[, 1] # Error!
arr2[:, 1] # 쉼표 앞은 생략이 불가하며 모든 row 선택시 콜론(:)을 사용

array([200, 500])

In [42]:
arr2[0, 1], arr2[0, :2] # 원소가 하나만 출력되는 경우 배열구조가 풀린다.

(200, array([100, 200]))

In [46]:
arr2[:, 0] == 400

array([False,  True])

In [45]:
arr2[arr2[:, 0] == 400, ] # row 필터링.

array([[400, 500, 600]])

### 유용한 함수

In [49]:
# range() 함수와 유사하나 결과 출력이 NumPy 배열이다.
np.arange(3), np.arange(1, 4), np.arange(5, 9, 2)

(array([0, 1, 2]), array([1, 2, 3]), array([5, 7]))

In [51]:
# np.where(조건, True일 때 반환값, False일 때 반환값)
np.where(arr1 > 100, "GT100", "LE100")

array(['GT100', 'LE100', 'LE100', 'GT100'], dtype='<U5')

In [52]:
np.where(arr1 > 100, 1, 0)

array([1, 0, 0, 1])

In [53]:
np.where(arr1 > 100, arr1, "LE100")

array(['999', 'LE100', 'LE100', '999'], dtype='<U11')

In [54]:
np.r_[:3, 5, 8:10] # 연속과 이산을 섞어 쓸 수 있다.

array([0, 1, 2, 5, 8, 9])

In [59]:
np.diag(np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])) # 대각 원소 추출

array([1, 5, 9])